apiVersion: v2
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: A Helm chart for MOSIP mimoto Application
home: https://mosip.io
keywords:
- mosip
- mimoto
maintainers:
- email: info@mosip.io
  name: MOSIP
name: mimoto
type: application
version: 0.20.0
